name: CI Pipeline

# Chạy workflow khi có sự kiện push hoặc pull request
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest # Sử dụng môi trường Ubuntu

    steps:
    # Bước 1: Check out mã nguồn
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Docker
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }} # Define these secrets in your GitHub repo
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # Build the Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/cicd_webapplication:latest .

    # Push the Docker image to Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cicd_webapplication:latest

    # Set up SSH to connect to Docker server
    - name: Thiết lập SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Pull image from Docker Hub on remote server and start container
    - name: Deploy to Docker Server
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        CONTAINER_NAME: ${{ secrets.CONTAINER_NAME_DEMO }}
        REPOSITORY_NAME: garydipprey
      run: |
        ssh -o StrictHostKeyChecking=no hnxadmin@${{ secrets.DOCKER_SERVER }} << 'EOF'
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/cicd_webapplication:latest
        docker stop ${{ secrets.CONTAINER_NAME_DEMO }} || true
        docker rm ${{ secrets.CONTAINER_NAME_DEMO }} || true
        docker run -d --name ${{ secrets.CONTAINER_NAME_DEMO }} -p 106:80 ${{ secrets.DOCKER_HUB_USERNAME }}/cicd_webapplication:latest
        EOF


